export const EVENT_ENTRY_QUEUE = "EVENT_ENTRY_QUEUE";
export const EVENT_ENTRY_PROCESS = "EVENT_CUSTOM_PROCESS";
export const EVENT_CLEAN_QUEUE = "EVENT_CLEAN_QUEUE";
export const EVENT_CLEAN_PROCESS = "EVENT_CLEAN_PROCESS";
export const CLICK_EVENT_QUEUE = "CLICK_EVENT_QUEUE";
export const CLICK_EVENT_PROCESS = "CLICK_EVENT_PROCESS";
